AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Utility Billing Job

Resources:
  MyLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-function
      Handler: app.lambda_handler
      Runtime: python3.11
      CodeUri: ./
      Timeout: 900
      MemorySize: 128
      Environment:
        Variables:
          TZ: America/Los_Angeles

          # Email
          SMTP_SERVER: "email-smtp.us-west-2.amazonaws.com"
          SMTP_PORT: "587"
          SMTP_USERNAME: ""
          SMTP_PASSWORD: ""
          NOTIFICATION_EMAIL: "Seaview Cottages COA - Accounts Receivable <ar@seaviewcottages.org>"
          NOTIFICATION_SENDER: "Auto-Bill <auto-bill@seaviewcottages.org>"

          # NextCentury
          NEXT_CENTURY_EMAIL: "ar@seaviewcottages.org"
          NEXT_CENTURY_PASSWORD: "{{resolve:ssm-secure:/lambda/utility-billing/next-century-password:1}}"

          # PayHOA
          PAY_HOA_CATEGORY_ID: "1038205"
          PAY_HOA_DEPOSIT_ACCOUNT: "38648"
          PAY_HOA_EMAIL: "ar+autobill@seaviewcottages.org"
          PAY_HOA_PASSWORD: "{{resolve:ssm-secure:/lambda/utility-billing/pay-hoa-password:1}}"
          PAY_HOA_ORGANIZATION_ID: "23133"
      Policies:
        - SSMParameterReadPolicy:
            ParameterName: !Sub /lambda/utility-billing/*
      Events:
        MonthlySchedule:
          Type: Schedule
          Properties:
            Schedule: cron(0 10 2 * ? *)
            Description: Monthly execution on the 2nd day at 10:00 UTC
            Enabled: true